language: node_js

node_js:
  - "node"

install:
  - npm install

script:
  - npm run lint

before_deploy:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  repo: luanvuvt/luanvuvt.github.io
  target-branch: master
  local-dir: ./public
  on:
    branch: master