language: node_js

install:
  - npm install

script:
  - npm run lint

jobs:
  include:
    - stage: deploy
      script: npm run build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        repo: luanvuvt/luanvuvt.github.io
        target-branch: master
        local-dir: ./public
        on:
          branch: master